### ISSUE TITLE
How to remove the search box ?

### ISSUE THREAD

**Issue by RenaudILTIS** [danpros/htmly#704]
I have a small static website, don't need the search box in the menu.

How to remove it, please ?
(Same for the RSS feed logo).

Thanks,
R.

**Comment by danpros** [comment]
Hi,

For search you can remove it manually in `layout.html.php`. In some themes eg. Clean theme:

```html
<div class="search">
    <?php echo search() ?>
</div>
```



For feed, you can using css to disable it, eg.

```css
.social-logo-feed {
  display: none !important;
}
```
